language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.6"
      env: TOXENV=py36 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "JvJhHNMKTChS9iodabFEMHogxFppa4SpHvSmylBN6U7iuu7nYRWPvE0fMBrONmmpY80b0hYQAUZMXINDEz5mNS5jgourE1LJBS++6gHiZB+wV2JEab5VzS49MyCZheklWk7j/LRH50AoOndwVvc8clUlfnR91DFEwumYcsB10/PiKLcLIOunY8WUw6e5h8LHERW2n25QTDqicAjGsFCEOVvAeEd3/OQdJA3WaYLRdkudeNtRWeAAnk6Agc1mC1LywleOZMocLLqseEOhswtKGJTdfQkZqiUn7ffeHd94bwEYS8k+cita336BbHA0mEhee4C/T0IJrrAHcnryrn8JspEYM7gtgjUTgWATJGfiuwDLe2ebzzKgRtE8XSLF4sXsHbO7slDRpUne98RjgMpueNUFaZZVEvwDHGp0eIqqicN0ehImy16OiKlvDUI8Pe4yjEdW0xFXz3khyFthRTGFReClLpOehoCyFzimxPfWT86ZgEs9ba5dZuY7HQU/umfp+Emh1CzdI6OzY8pus0lHa2YRXjM6u9Dnb7fTdED01Xt3dTIqzVOP9+7NS+i93rvav2R5jJmBnArrBNVtEh35D2Bn7KX02shHBAP7eqYTbd+WGRhn2ck67Ddj5RvETTAO0brzNkUh+IsY5GrTekgCgpN8AXFieeFkf7GtaRFyDOo="
    api_key:
      secure: "C+aj5S5h9aag3VykdxgSVKXrZqwmIGMosrgBsqzmJ3GmybinwKmcu38rsYcl0x/VvxUmkBEMWuxdHGtFlOdsu2Z0PodOsjuJMchsExXsVPRsb+L7CXRIANGlvzy/9eEkJE77qN6Za8EU6aFgNTOI7n3CVfOsEq8NW3MVsQ/urYByAKgnSq9redIGepcXB2QVfRjZaVQNyEw/7b7mdvGygYGuM15QTFnf88QOxbf8ZxMB5AMbQxW93Q+MngLhel3qOrN2LAuCD/hAwWBlYkYUIuMNBGd/4V++a3m1KZfn0QQXMP0EziaUKIi2KbDlx7VyIVpDIxqnNQ7pxeQD+PnoX+Wsj1curj/Y21gfnOIK8Pk3IdfzKC03+mKvq3vFMpb8oKNMPK2ow/kskwt72xxfvLLHTQ4TbF7ynabDDQ8fG+DHp8ytIXcA5Bs6mQx8gHeck/033koz0NEXeeGdW5l/DMITe6QB5bZcEw1jZhvHOod75pQqs6s/098QQUewdRFQgXq/20BKg6i12byF8DOCjgNliWD8p0fjjcJilijZUlZprNAtk3bHcpWVHAVnTJtdtvs7qcdlZvDIBv68G2BnLGA9RzWh67IhaTrdnJ4xb98P1o5X5ZI2gXlmAyrmGyp+2p/fp3KYlg2m5T6tb3bsHptREV/BBHewssDsklWRmww="
branches:
  except:
    - "/^noci-.*$/"
